version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hkt-sh"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15gznv4ri5gex"
s3_prefix = "hkt-sh"
region = "ap-northeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
