AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hkt.sh

Globals:
  Function:
    Timeout: 5

Resources:
  HomeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: home/home.zip
      Handler: home
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /
            Method: GET
      Environment:
        Variables:
          PARAM1: VALUE
  EntryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: entry/entry.zip
      Handler: entry
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /{name}
            Method: GET
      Environment:
        Variables:
          PARAM1: VALUE

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HomeAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HomeFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt HomeFunction.Arn
  HomeFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HomeFunctionRole.Arn
